import { Project, Category, ProjectPack } from "./types";

export const CATEGORIES: Category[] = [
  {
    id: "ai-ml",
    name: "AI & Machine Learning",
    description: "Python, ML, prediction, classification, neural networks",
    icon: "🧠",
    color: "#7C3AED",
  },
  {
    id: "generative-ai",
    name: "Generative AI",
    description: "LLMs, RAG, chatbots, document intelligence, GPT",
    icon: "✨",
    color: "#06B6D4",
  },
  {
    id: "ai-agents",
    name: "AI Agents",
    description: "Multi-agent systems, automation, tool calling, orchestration",
    icon: "🤖",
    color: "#8B5CF6",
  },
  {
    id: "full-stack",
    name: "Full Stack",
    description: "React, Next.js, Node.js, Python, databases, APIs",
    icon: "🌐",
    color: "#10B981",
  },
  {
    id: "data-science",
    name: "Data Science",
    description: "Analytics, visualization, predictive modeling, dashboards",
    icon: "📊",
    color: "#F59E0B",
  },
  {
    id: "computer-vision",
    name: "Computer Vision",
    description: "OpenCV, YOLO, image processing, object detection",
    icon: "👁️",
    color: "#EC4899",
  },
  {
    id: "cybersecurity",
    name: "Cybersecurity",
    description: "Security analytics, phishing detection, authentication",
    icon: "🛡️",
    color: "#EF4444",
  },
  {
    id: "cloud-devops",
    name: "Cloud & DevOps",
    description: "Docker, CI/CD, cloud deployment, infrastructure",
    icon: "☁️",
    color: "#3B82F6",
  },
  {
    id: "mobile",
    name: "Mobile Development",
    description: "Flutter, Android, mobile applications",
    icon: "📱",
    color: "#14B8A6",
  },
  {
    id: "final-year",
    name: "Final Year Projects",
    description: "Advanced multidisciplinary projects for engineering students",
    icon: "🎓",
    color: "#F97316",
  },
];

export const PROJECTS: Project[] = [
  // ═══════════════════════════════════════
  // FINAL YEAR PROJECTS (10 Flagship)
  // ═══════════════════════════════════════
  {
    id: "fyp-01",
    slug: "ai-smart-hospital-management",
    title: "AI-Powered Smart Hospital Management & Clinical Decision Support System",
    shortDescription:
      "A comprehensive hospital management platform with AI-powered clinical decision support, patient diagnosis assistance, and smart resource allocation.",
    fullDescription: `This project builds a complete AI-powered hospital management system that integrates clinical decision support, patient record management, appointment scheduling, inventory tracking, and predictive analytics — all in one unified platform.

The system leverages Machine Learning models to analyze patient vitals and medical history to provide clinical decision support to doctors, flagging critical patterns and suggesting diagnostic pathways. Built with a modern full-stack architecture, the platform serves doctors, nurses, administrators, and patients through role-based access control.

**Problem Being Solved:**
Hospitals lose critical time to manual paperwork, fragmented systems, and delayed decision-making. This system centralizes operations and augments clinical decisions with AI intelligence.

**Who It's For:**
Engineering students pursuing final year projects in AI + Healthcare, software engineering, or full-stack development. Excellent for portfolios targeting MNC healthcare tech roles.`,
    category: "final-year",
    difficulty: "Advanced",
    isFinalYear: true,
    isFeatured: true,
    technologies: ["Python", "FastAPI", "React", "PostgreSQL", "TensorFlow", "Docker"],
    tags: ["healthcare", "ai", "machine learning", "hospital", "clinical decision support", "final year"],
    price: 2499,
    tier: "Premium",
    features: [
      "AI-powered clinical decision support engine",
      "Patient record management (EHR)",
      "Smart appointment scheduling with conflict detection",
      "Doctor & staff management portal",
      "Inventory & pharmacy management",
      "Real-time patient vitals monitoring dashboard",
      "Predictive readmission risk scoring",
      "Role-based access control (Admin/Doctor/Nurse/Patient)",
      "Billing and insurance management",
      "Analytics and reporting dashboard",
    ],
    includes: [
      "Complete source code (Frontend + Backend)",
      "Database schema and seed data",
      "Architecture diagrams (UML, ER, Flow)",
      "SRS document",
      "Project abstract and problem statement",
      "Literature survey",
      "30-slide presentation (PPT)",
      "Installation and deployment guide",
      "API documentation",
      "Viva questions and model answers",
      "Code explanation walkthrough",
      "Portfolio description",
      "LinkedIn project writeup",
    ],
    learningOutcomes: [
      "Full-stack web development with React and FastAPI",
      "Machine learning model integration in production",
      "Database design for healthcare systems",
      "Role-based authentication and authorization",
      "REST API design and documentation",
      "Docker containerization and deployment",
      "Data visualization with charts and dashboards",
    ],
    requirements: [
      "Python 3.9+ and Node.js 18+",
      "PostgreSQL database",
      "Basic knowledge of React and Python",
      "4GB RAM minimum for running locally",
    ],
    modules: [
      { name: "Patient Management", description: "Complete EHR system with registration, history, and records" },
      { name: "Clinical Decision Support", description: "ML-powered diagnostic suggestions and risk flagging" },
      { name: "Appointment System", description: "Smart scheduling with doctor availability and conflict resolution" },
      { name: "Inventory & Pharmacy", description: "Medicine stock tracking with automatic reorder alerts" },
      { name: "Billing & Insurance", description: "Invoice generation and insurance claim tracking" },
      { name: "Analytics Dashboard", description: "Hospital KPIs, patient trends, and revenue analytics" },
    ],
    techStack: {
      frontend: ["React", "TypeScript", "Tailwind CSS", "Chart.js"],
      backend: ["Python", "FastAPI", "SQLAlchemy"],
      database: ["PostgreSQL", "Redis"],
      aiml: ["TensorFlow", "scikit-learn", "Pandas", "NumPy"],
      deployment: ["Docker", "Nginx"],
    },
    licenseType: "Academic",
    status: "published",
    faqs: [
      {
        question: "Can I use this for my college final year project submission?",
        answer: "Yes, this project is specifically designed as a learning resource for final year students. You should understand the code, customize it, and reference the documentation provided.",
      },
      {
        question: "Is the ML model pre-trained or do I need to train it?",
        answer: "The ML models come pre-trained with sample data. The training scripts and dataset are included so you can retrain with real data.",
      },
    ],
  },
  {
    id: "fyp-02",
    slug: "ai-college-assistant-rag",
    title: "AI College Assistant & Academic RAG Platform",
    shortDescription:
      "An intelligent college assistant powered by RAG (Retrieval-Augmented Generation) that answers student queries from academic documents, syllabus, and college policies.",
    fullDescription: `Build a next-generation AI-powered college assistant that uses RAG architecture to intelligently answer questions from uploaded academic documents — syllabus, exam schedules, college rules, faculty information, and more.

The system processes uploaded PDFs and documents using vector embeddings, stores them in a vector database, and uses an LLM to generate accurate, contextual answers grounded in real college data — eliminating hallucinations.

**Key Innovation:** Students can simply ask questions like "When is the ML exam?" or "What is the attendance requirement?" and get instant, accurate answers from official documents.

**Technical Excellence:** This project demonstrates cutting-edge GenAI skills — RAG pipelines, vector databases, LLM integration — skills that are in extremely high demand at AI companies.`,
    category: "generative-ai",
    difficulty: "Advanced",
    isFinalYear: true,
    isFeatured: true,
    technologies: ["Python", "LangChain", "React", "FAISS", "OpenAI", "FastAPI"],
    tags: ["generative ai", "rag", "langchain", "llm", "chatbot", "education", "final year"],
    price: 2499,
    tier: "Premium",
    features: [
      "RAG-based question answering from uploaded documents",
      "PDF and document ingestion pipeline",
      "Vector embedding storage with FAISS",
      "Conversation history with context memory",
      "Multi-document support",
      "Admin panel for document management",
      "User authentication",
      "Chat interface with markdown rendering",
      "Source citation in answers",
      "Analytics on popular questions",
    ],
    includes: [
      "Complete source code",
      "RAG pipeline implementation",
      "Vector database setup guide",
      "API documentation",
      "Architecture diagrams",
      "Project abstract and SRS",
      "Literature survey on RAG systems",
      "40-slide PPT",
      "Viva Q&A (RAG, LLMs, vector databases)",
      "Deployment guide",
      "Portfolio and LinkedIn description",
    ],
    learningOutcomes: [
      "RAG (Retrieval-Augmented Generation) architecture",
      "Vector databases and embeddings",
      "LangChain framework for LLM applications",
      "PDF processing and text chunking strategies",
      "FastAPI for AI-powered backends",
      "Prompt engineering",
      "Full-stack integration with AI backends",
    ],
    requirements: [
      "Python 3.10+",
      "OpenAI API key (or compatible LLM provider)",
      "Node.js 18+ for frontend",
      "Basic Python and React knowledge",
    ],
    modules: [
      { name: "Document Ingestion", description: "PDF upload, text extraction, chunking, and embedding generation" },
      { name: "Vector Store", description: "FAISS-based similarity search for relevant document chunks" },
      { name: "RAG Pipeline", description: "LangChain orchestration for retrieval + generation" },
      { name: "Chat Interface", description: "React-based conversational UI with history" },
      { name: "Admin Panel", description: "Document management and analytics" },
    ],
    techStack: {
      frontend: ["React", "TypeScript", "Tailwind CSS"],
      backend: ["Python", "FastAPI", "LangChain"],
      database: ["FAISS", "SQLite"],
      aiml: ["OpenAI GPT", "sentence-transformers", "LangChain"],
      apis: ["OpenAI API"],
    },
    licenseType: "Academic",
    status: "published",
    faqs: [
      {
        question: "Can I use a free LLM instead of OpenAI?",
        answer: "Yes, the project supports Ollama (local LLMs) as an alternative. Instructions are included in the documentation.",
      },
    ],
  },
  {
    id: "fyp-03",
    slug: "ai-resume-screening-job-matching",
    title: "AI Resume Screening, Job Matching & Career Recommendation System",
    shortDescription:
      "An NLP-powered platform that automatically screens resumes, matches candidates to job descriptions, and recommends career paths based on skill gap analysis.",
    fullDescription: `This project creates a complete AI-powered recruitment intelligence platform that automates resume screening, performs semantic job-candidate matching, and provides data-driven career recommendations.

The system uses NLP techniques to parse resumes, extract skills, experience, and education data, then matches these against job requirements using semantic similarity. An ML model predicts match scores and ranks candidates automatically.

**Real-world application:** This is exactly the type of system used by companies like LinkedIn, Naukri, and recruitment platforms — making it an excellent portfolio project for roles in AI, data science, and software engineering.`,
    category: "ai-ml",
    difficulty: "Advanced",
    isFinalYear: true,
    isFeatured: true,
    technologies: ["Python", "spaCy", "React", "FastAPI", "PostgreSQL", "scikit-learn"],
    tags: ["nlp", "resume screening", "job matching", "career", "machine learning", "final year"],
    price: 2299,
    tier: "Premium",
    features: [
      "Automated resume parsing with NLP",
      "Skill extraction and normalization",
      "Semantic job-candidate matching engine",
      "Match score calculation and ranking",
      "Career gap analysis and recommendations",
      "Job posting management for recruiters",
      "Candidate dashboard with analytics",
      "Batch processing for multiple resumes",
      "Integration-ready REST API",
      "Admin analytics dashboard",
    ],
    includes: [
      "Complete source code",
      "Pre-trained NLP models",
      "Sample dataset of resumes and job descriptions",
      "API documentation",
      "Architecture diagrams",
      "SRS and abstract",
      "Literature survey on NLP recruitment systems",
      "35-slide PPT",
      "Viva Q&A",
      "Installation guide",
      "Portfolio description",
    ],
    learningOutcomes: [
      "Natural Language Processing with spaCy",
      "Text vectorization and semantic similarity",
      "Resume parsing techniques",
      "ML model training for classification/ranking",
      "REST API design with FastAPI",
      "Data processing pipelines",
      "Full-stack application architecture",
    ],
    requirements: ["Python 3.9+", "Node.js 18+", "PostgreSQL", "4GB RAM for NLP models"],
    modules: [
      { name: "Resume Parser", description: "NLP-based extraction of skills, education, and experience" },
      { name: "Job Matcher", description: "Semantic similarity scoring between resumes and job descriptions" },
      { name: "Career Advisor", description: "Skill gap analysis and career path recommendations" },
      { name: "Recruiter Portal", description: "Job posting, candidate management, and shortlisting" },
      { name: "Candidate Dashboard", description: "Profile management, job applications, and match scores" },
    ],
    techStack: {
      frontend: ["React", "TypeScript", "Recharts"],
      backend: ["Python", "FastAPI"],
      database: ["PostgreSQL"],
      aiml: ["spaCy", "scikit-learn", "sentence-transformers", "NLTK"],
    },
    licenseType: "Academic",
    status: "published",
  },
  {
    id: "fyp-04",
    slug: "smart-campus-management-ai",
    title: "Smart Campus Management System with AI Assistant",
    shortDescription:
      "A comprehensive digital campus platform with AI-powered assistance, smart attendance, event management, facility booking, and academic administration.",
    fullDescription: `This project delivers a complete smart campus ecosystem — combining IoT simulation, AI assistance, and digital administration for modern educational institutions.

Features include AI-powered student query resolution, automated attendance tracking, facility booking, event management, academic performance analytics, and a unified portal for students, faculty, and administrators.

The AI assistant understands natural language and can answer questions about schedules, grades, policies, and campus resources — making this a highly practical and demonstrable project for final year evaluations.`,
    category: "full-stack",
    difficulty: "Advanced",
    isFinalYear: true,
    isFeatured: false,
    technologies: ["Next.js", "Python", "Firebase", "OpenAI", "Tailwind CSS"],
    tags: ["campus management", "full stack", "ai assistant", "education", "final year"],
    price: 2499,
    tier: "Premium",
    features: [
      "AI-powered campus assistant (NLP Q&A)",
      "Smart attendance system with analytics",
      "Facility and room booking",
      "Event management and notifications",
      "Academic performance dashboard",
      "Faculty management portal",
      "Student portal with grades and timetable",
      "Announcement and notice board",
      "Lost and found reporting",
      "Admin control panel",
    ],
    includes: [
      "Complete source code",
      "Firebase setup and rules",
      "Architecture diagrams",
      "SRS document",
      "Abstract and problem statement",
      "Literature survey",
      "35-slide PPT",
      "Installation guide",
      "API documentation",
      "Viva questions and answers",
      "Portfolio description",
    ],
    learningOutcomes: [
      "Next.js App Router and server components",
      "Firebase Firestore real-time database",
      "OpenAI API integration",
      "Role-based authentication",
      "Complex UI/UX with Tailwind CSS",
      "Real-time notifications",
      "Data visualization",
    ],
    requirements: ["Node.js 18+", "Firebase project", "OpenAI API key", "Basic React knowledge"],
    modules: [
      { name: "AI Assistant", description: "LLM-powered chatbot for campus queries" },
      { name: "Attendance System", description: "QR or manual attendance with analytics" },
      { name: "Academic Portal", description: "Grades, timetable, and course management" },
      { name: "Facility Booking", description: "Room and equipment reservation system" },
      { name: "Event Manager", description: "Campus events, registrations, and notifications" },
    ],
    techStack: {
      frontend: ["Next.js", "TypeScript", "Tailwind CSS"],
      backend: ["Next.js API Routes", "Python (AI module)"],
      database: ["Firebase Firestore", "Firebase Storage"],
      aiml: ["OpenAI GPT-4"],
      apis: ["OpenAI API", "Firebase Admin"],
    },
    licenseType: "Academic",
    status: "published",
  },
  {
    id: "fyp-05",
    slug: "ai-fraud-detection-financial-risk",
    title: "AI-Based Fraud Detection & Financial Risk Analysis System",
    shortDescription:
      "A machine learning system that detects fraudulent transactions in real-time, performs risk scoring, and provides financial analysts with explainable AI insights.",
    fullDescription: `This project builds a production-grade fraud detection system using ensemble machine learning methods to identify suspicious financial transactions with high accuracy and low false-positive rates.

The system processes transaction data in real-time, applies trained ML models to compute fraud probability scores, and provides explainable AI (XAI) insights to help analysts understand why a transaction was flagged.

**Industry Relevance:** Fraud detection is a core use case in fintech and banking. This project demonstrates data science, ML engineering, and explainability skills valued by companies like PayTM, Razorpay, and major banks.`,
    category: "ai-ml",
    difficulty: "Advanced",
    isFinalYear: true,
    isFeatured: false,
    technologies: ["Python", "scikit-learn", "XGBoost", "React", "FastAPI", "SHAP"],
    tags: ["fraud detection", "machine learning", "fintech", "xgboost", "explainable ai", "final year"],
    price: 2299,
    tier: "Premium",
    features: [
      "Real-time transaction fraud scoring",
      "Ensemble ML model (XGBoost + Random Forest)",
      "Explainable AI with SHAP values",
      "Risk dashboard for analysts",
      "Transaction history and audit log",
      "Alert system for high-risk transactions",
      "Model performance metrics",
      "Data preprocessing pipeline",
      "REST API for integration",
      "Admin panel",
    ],
    includes: [
      "Complete source code",
      "Pre-trained ML models",
      "Sample transaction dataset",
      "Model training notebooks",
      "Architecture diagrams",
      "SRS and abstract",
      "Literature survey on fraud detection",
      "35-slide PPT",
      "Viva Q&A",
      "Installation guide",
    ],
    learningOutcomes: [
      "Fraud detection techniques and algorithms",
      "XGBoost and ensemble methods",
      "SHAP for model explainability",
      "Handling imbalanced datasets (SMOTE)",
      "Feature engineering for financial data",
      "REST API development",
      "Data visualization for analytics",
    ],
    requirements: ["Python 3.9+", "Node.js 18+", "4GB RAM", "Basic ML knowledge"],
    modules: [
      { name: "Data Pipeline", description: "Transaction ingestion, preprocessing, and feature engineering" },
      { name: "ML Engine", description: "Ensemble model for fraud scoring" },
      { name: "Explainability Module", description: "SHAP-based explanations for flagged transactions" },
      { name: "Risk Dashboard", description: "Real-time monitoring and alert system" },
      { name: "Admin Panel", description: "Model management and system configuration" },
    ],
    techStack: {
      frontend: ["React", "TypeScript", "Recharts", "Tailwind CSS"],
      backend: ["Python", "FastAPI"],
      database: ["PostgreSQL", "Redis"],
      aiml: ["XGBoost", "scikit-learn", "SHAP", "imbalanced-learn", "Pandas"],
    },
    licenseType: "Academic",
    status: "published",
  },
  {
    id: "fyp-06",
    slug: "intelligent-traffic-monitoring-accident-detection",
    title: "Intelligent Traffic Monitoring & Accident Detection System",
    shortDescription:
      "A computer vision system that monitors traffic density, detects accidents in real-time from CCTV feeds, and triggers automated emergency alerts.",
    fullDescription: `This project implements an end-to-end intelligent traffic management system using computer vision and deep learning to monitor traffic flow, detect accidents, identify traffic violations, and automatically trigger emergency response alerts.

The system processes video feeds (live or recorded), applies YOLO object detection to identify vehicles, accidents, and violations, and provides real-time analytics on a web dashboard.

**Demonstrability:** This project has excellent visual demonstrations — you can show real-time detection working on video feeds, making it highly impressive for final year presentations and viva examinations.`,
    category: "computer-vision",
    difficulty: "Advanced",
    isFinalYear: true,
    isFeatured: true,
    technologies: ["Python", "YOLO", "OpenCV", "React", "FastAPI", "WebSockets"],
    tags: ["computer vision", "yolo", "traffic monitoring", "accident detection", "opencv", "final year"],
    price: 2499,
    tier: "Premium",
    features: [
      "Real-time vehicle detection with YOLO",
      "Accident detection from video feeds",
      "Traffic density analysis and reporting",
      "Speed estimation for vehicles",
      "Traffic violation detection",
      "Automated emergency alert system",
      "Live dashboard with video stream",
      "Historical analytics and reports",
      "Multi-camera support",
      "Alert notification system",
    ],
    includes: [
      "Complete source code",
      "Pre-trained YOLO model weights",
      "Sample video datasets",
      "Architecture diagrams",
      "SRS and abstract",
      "Literature survey on CV traffic systems",
      "35-slide PPT",
      "Viva Q&A",
      "Installation guide",
      "Portfolio description",
    ],
    learningOutcomes: [
      "YOLO object detection model usage",
      "OpenCV video processing",
      "Computer vision pipelines",
      "WebSocket real-time streaming",
      "FastAPI for ML model serving",
      "React dashboard with live data",
    ],
    requirements: [
      "Python 3.9+",
      "NVIDIA GPU recommended (CPU also works)",
      "Node.js 18+",
      "Basic Python and CV knowledge",
    ],
    modules: [
      { name: "Detection Engine", description: "YOLO-based real-time vehicle and incident detection" },
      { name: "Video Stream Processor", description: "Frame extraction, processing, and analysis" },
      { name: "Alert System", description: "Automated emergency notifications on accident detection" },
      { name: "Analytics Dashboard", description: "Real-time traffic stats and historical reports" },
      { name: "Camera Manager", description: "Multi-feed configuration and monitoring" },
    ],
    techStack: {
      frontend: ["React", "TypeScript", "WebSockets", "Chart.js"],
      backend: ["Python", "FastAPI", "WebSockets"],
      database: ["PostgreSQL"],
      aiml: ["YOLOv8", "OpenCV", "NumPy", "Supervision"],
    },
    licenseType: "Academic",
    status: "published",
  },
  {
    id: "fyp-07",
    slug: "ai-crop-disease-detection-agriculture",
    title: "AI-Based Crop Disease Detection & Smart Agriculture Platform",
    shortDescription:
      "A computer vision and ML platform that detects crop diseases from leaf images, provides treatment recommendations, and offers smart farming analytics.",
    fullDescription: `This project delivers a comprehensive smart agriculture platform that uses deep learning to identify crop diseases from photographs taken by farmers' smartphones, then provides actionable treatment recommendations.

The CNN-based model is trained to classify 38 different plant diseases across multiple crops. The mobile-friendly web application allows farmers to upload photos and receive instant diagnosis with confidence scores and treatment guidance.

**Social Impact:** This project addresses a critical real-world problem — crop diseases cause 20-40% yield loss globally. The combination of AI + agriculture makes it stand out as a meaningful and innovative project.`,
    category: "computer-vision",
    difficulty: "Advanced",
    isFinalYear: true,
    isFeatured: false,
    technologies: ["Python", "TensorFlow", "React", "FastAPI", "PostgreSQL"],
    tags: ["agriculture", "crop disease", "computer vision", "tensorflow", "cnn", "final year"],
    price: 2299,
    tier: "Premium",
    features: [
      "CNN model for crop disease classification (38 classes)",
      "Image upload and real-time disease detection",
      "Treatment and fertilizer recommendations",
      "Crop health monitoring dashboard",
      "Farmer community forum",
      "Weather integration for smart alerts",
      "Historical diagnosis records",
      "Expert consultation booking",
      "Mobile-responsive interface",
    ],
    includes: [
      "Complete source code",
      "Pre-trained CNN model",
      "Training scripts and dataset links",
      "Architecture diagrams",
      "SRS and abstract",
      "Literature survey",
      "30-slide PPT",
      "Viva Q&A",
      "Installation guide",
    ],
    learningOutcomes: [
      "Convolutional Neural Networks (CNN)",
      "Transfer learning with ResNet/EfficientNet",
      "Image classification pipeline",
      "Model deployment with FastAPI",
      "Mobile-first web design",
      "Real-world AI application development",
    ],
    requirements: ["Python 3.9+", "TensorFlow 2.x", "Node.js 18+", "4GB RAM minimum"],
    modules: [
      { name: "Disease Detection", description: "CNN-powered image classification for 38 plant diseases" },
      { name: "Recommendation Engine", description: "Treatment plans based on disease identification" },
      { name: "Farmer Portal", description: "Upload, diagnose, and track crop health" },
      { name: "Weather Integration", description: "Disease risk alerts based on weather patterns" },
      { name: "Admin Dashboard", description: "Usage analytics and system management" },
    ],
    techStack: {
      frontend: ["React", "TypeScript", "Tailwind CSS"],
      backend: ["Python", "FastAPI"],
      database: ["PostgreSQL"],
      aiml: ["TensorFlow", "Keras", "OpenCV", "Pillow"],
    },
    licenseType: "Academic",
    status: "published",
  },
  {
    id: "fyp-08",
    slug: "ai-cybersecurity-threat-phishing-detection",
    title: "AI-Powered Cybersecurity Threat & Phishing Detection Platform",
    shortDescription:
      "A machine learning security platform that detects phishing URLs, malware patterns, and network threats in real-time with explainable AI analysis.",
    fullDescription: `This project creates an AI-powered cybersecurity intelligence platform that detects phishing websites, analyzes suspicious URLs, identifies malware patterns, and provides security threat analytics — all backed by machine learning models.

The system combines multiple ML models trained on real threat intelligence datasets to provide high-accuracy detection. A web interface allows security analysts to investigate threats, visualize attack patterns, and generate reports.

**Career Relevance:** Cybersecurity + AI is one of the fastest-growing career domains. This project demonstrates skills sought by cybersecurity companies, government agencies, and large enterprises.`,
    category: "cybersecurity",
    difficulty: "Advanced",
    isFinalYear: true,
    isFeatured: false,
    technologies: ["Python", "scikit-learn", "React", "FastAPI", "SQLite"],
    tags: ["cybersecurity", "phishing detection", "machine learning", "threat detection", "final year"],
    price: 2499,
    tier: "Premium",
    features: [
      "Real-time URL phishing detection",
      "ML-based malware pattern analysis",
      "Network traffic anomaly detection",
      "Threat intelligence dashboard",
      "IP reputation checking",
      "Bulk URL scanning via API",
      "Alert and notification system",
      "Security report generation",
      "Historical threat analysis",
      "Explainable AI for flagged threats",
    ],
    includes: [
      "Complete source code",
      "Pre-trained security models",
      "Threat dataset documentation",
      "Architecture diagrams",
      "SRS and abstract",
      "Literature survey on AI security",
      "30-slide PPT",
      "Viva Q&A",
      "Installation guide",
    ],
    learningOutcomes: [
      "ML-based threat detection techniques",
      "Feature engineering for security data",
      "API development for security tools",
      "Data visualization for security analytics",
      "Model explainability in security",
      "Cybersecurity fundamentals",
    ],
    requirements: ["Python 3.9+", "Node.js 18+", "2GB RAM minimum"],
    modules: [
      { name: "Phishing Detector", description: "URL analysis and phishing probability scoring" },
      { name: "Malware Analyzer", description: "File pattern analysis for malware indicators" },
      { name: "Network Monitor", description: "Traffic anomaly detection and alerting" },
      { name: "Threat Dashboard", description: "Real-time security intelligence visualization" },
      { name: "API Gateway", description: "Bulk scanning and integration endpoints" },
    ],
    techStack: {
      frontend: ["React", "TypeScript", "Recharts"],
      backend: ["Python", "FastAPI"],
      database: ["SQLite", "Redis"],
      aiml: ["scikit-learn", "XGBoost", "SHAP", "Pandas"],
    },
    licenseType: "Academic",
    status: "published",
  },
  {
    id: "fyp-09",
    slug: "multi-agent-ai-research-assistant",
    title: "Multi-Agent AI Research & Knowledge Assistant",
    shortDescription:
      "An agentic AI system with multiple specialized agents that collaborate to research topics, synthesize knowledge from multiple sources, and generate comprehensive research reports.",
    fullDescription: `This project implements a sophisticated multi-agent AI system where specialized agents collaborate autonomously to accomplish complex research tasks — one agent searches the web, another analyzes papers, a third synthesizes findings, and a fourth generates reports.

Built with LangGraph for agent orchestration, this project represents the cutting edge of AI engineering — agentic workflows with tool use, memory, and collaborative intelligence.

**Career Impact:** Agentic AI is the next frontier in AI engineering. This project will stand out dramatically in portfolios targeting roles at AI startups, research labs, and MNCs building AI products.`,
    category: "ai-agents",
    difficulty: "Advanced",
    isFinalYear: true,
    isFeatured: true,
    technologies: ["Python", "LangGraph", "LangChain", "OpenAI", "React", "FastAPI"],
    tags: ["ai agents", "langgraph", "multi-agent", "research assistant", "agentic ai", "final year"],
    price: 2999,
    tier: "Premium",
    features: [
      "Multi-agent orchestration with LangGraph",
      "Web research agent with real-time search",
      "Document analysis agent",
      "Knowledge synthesis agent",
      "Report generation agent",
      "Agent conversation visualization",
      "Research history and management",
      "Export to PDF/Markdown",
      "Collaborative research sessions",
      "Custom agent configuration",
    ],
    includes: [
      "Complete source code",
      "Agent workflow diagrams",
      "LangGraph configuration",
      "Architecture diagrams",
      "SRS and abstract",
      "Literature survey on multi-agent systems",
      "40-slide PPT",
      "Viva Q&A (agentic AI, LangGraph, LLMs)",
      "Installation guide",
      "Portfolio description",
    ],
    learningOutcomes: [
      "Multi-agent AI system design",
      "LangGraph for agent orchestration",
      "Tool use and function calling",
      "Agent memory and state management",
      "LLM prompt engineering for agents",
      "FastAPI for AI backends",
      "Complex async Python",
    ],
    requirements: [
      "Python 3.11+",
      "OpenAI API key",
      "Node.js 18+",
      "Intermediate Python knowledge",
    ],
    modules: [
      { name: "Research Orchestrator", description: "LangGraph-based multi-agent coordination" },
      { name: "Web Search Agent", description: "Real-time web research and content extraction" },
      { name: "Analysis Agent", description: "Document reading and insight extraction" },
      { name: "Synthesis Agent", description: "Knowledge consolidation and gap identification" },
      { name: "Report Generator", description: "Structured research report creation" },
    ],
    techStack: {
      frontend: ["React", "TypeScript", "Tailwind CSS"],
      backend: ["Python", "FastAPI", "LangGraph", "LangChain"],
      database: ["Redis", "SQLite"],
      aiml: ["OpenAI GPT-4", "LangGraph", "LangChain"],
      apis: ["OpenAI API", "Tavily Search API"],
    },
    licenseType: "Academic",
    status: "published",
  },
  {
    id: "fyp-10",
    slug: "ai-personalized-learning-performance-prediction",
    title: "AI-Based Personalized Learning & Student Performance Prediction Platform",
    shortDescription:
      "An adaptive learning platform that personalizes content delivery based on student performance, predicts at-risk students early, and recommends targeted interventions.",
    fullDescription: `This project creates an intelligent EdTech platform that uses machine learning to understand each student's learning patterns, predict academic performance, identify at-risk students early, and dynamically adjust content recommendations.

The system collects learning analytics data (time spent, quiz scores, engagement patterns), trains ML models to predict performance, and serves personalized content through an adaptive learning engine.

**EdTech + AI** is a high-growth market. This project demonstrates both AI engineering and EdTech product thinking — an excellent combination for student resumes.`,
    category: "ai-ml",
    difficulty: "Advanced",
    isFinalYear: true,
    isFeatured: false,
    technologies: ["Python", "scikit-learn", "React", "FastAPI", "PostgreSQL"],
    tags: ["edtech", "personalized learning", "student performance", "machine learning", "final year"],
    price: 2299,
    tier: "Premium",
    features: [
      "Student performance prediction model",
      "At-risk student early warning system",
      "Personalized content recommendations",
      "Adaptive quiz difficulty adjustment",
      "Learning path generation",
      "Teacher analytics dashboard",
      "Student progress tracking",
      "Intervention recommendation system",
      "Gamification elements",
      "Parent notification portal",
    ],
    includes: [
      "Complete source code",
      "ML model training notebooks",
      "Sample educational dataset",
      "Architecture diagrams",
      "SRS and abstract",
      "Literature survey",
      "30-slide PPT",
      "Viva Q&A",
      "Installation guide",
    ],
    learningOutcomes: [
      "ML model development for prediction",
      "Learning analytics and data collection",
      "Recommendation system design",
      "Data-driven product thinking",
      "FastAPI and React integration",
      "PostgreSQL data modeling",
    ],
    requirements: ["Python 3.9+", "Node.js 18+", "PostgreSQL", "2GB RAM"],
    modules: [
      { name: "Performance Predictor", description: "ML model for early academic performance prediction" },
      { name: "Recommendation Engine", description: "Personalized content and learning path recommendations" },
      { name: "Adaptive Assessment", description: "Dynamic difficulty adjustment based on performance" },
      { name: "Teacher Dashboard", description: "Class analytics, at-risk alerts, and interventions" },
      { name: "Student Portal", description: "Personalized learning journey and progress tracking" },
    ],
    techStack: {
      frontend: ["React", "TypeScript", "Chart.js", "Tailwind CSS"],
      backend: ["Python", "FastAPI"],
      database: ["PostgreSQL"],
      aiml: ["scikit-learn", "XGBoost", "Pandas", "NumPy"],
    },
    licenseType: "Academic",
    status: "published",
  },

  // ═══════════════════════════════════════
  // GENERATIVE AI PROJECTS
  // ═══════════════════════════════════════
  {
    id: "gen-01",
    slug: "ai-interview-preparation-system",
    title: "AI Interview Preparation System",
    shortDescription:
      "Practice technical and HR interviews with an AI interviewer that gives real-time feedback, evaluates answers, and generates personalized improvement plans.",
    fullDescription: "An AI-powered interview practice platform where students can simulate real technical and HR interviews, receive instant AI evaluation of their answers, get scored on communication and content quality, and receive personalized improvement suggestions.",
    category: "generative-ai",
    difficulty: "Intermediate",
    isFinalYear: false,
    isFeatured: true,
    technologies: ["Python", "OpenAI", "React", "FastAPI", "SQLite"],
    tags: ["interview prep", "generative ai", "openai", "career", "chatgpt"],
    price: 1499,
    tier: "Professional",
    features: [
      "AI-generated interview questions by role and difficulty",
      "Real-time answer evaluation with feedback",
      "Speech-to-text input support",
      "Performance analytics and scoring",
      "Topic-wise question banks",
      "Personalized improvement suggestions",
      "Mock interview session history",
    ],
    includes: [
      "Complete source code",
      "Question bank datasets",
      "API documentation",
      "Installation guide",
      "PPT (20 slides)",
      "Portfolio description",
    ],
    learningOutcomes: ["OpenAI API integration", "Prompt engineering", "React frontend development", "FastAPI backend"],
    requirements: ["Python 3.10+", "OpenAI API key", "Node.js 18+"],
    modules: [
      { name: "Question Engine", description: "AI-generated contextual interview questions" },
      { name: "Answer Evaluator", description: "LLM-based answer quality assessment" },
      { name: "Analytics", description: "Performance tracking and improvement suggestions" },
    ],
    techStack: {
      frontend: ["React", "TypeScript"],
      backend: ["Python", "FastAPI"],
      aiml: ["OpenAI GPT-4"],
      database: ["SQLite"],
    },
    licenseType: "Personal Learning",
    status: "published",
  },
  {
    id: "gen-02",
    slug: "ai-document-analyzer",
    title: "AI Document Analyzer",
    shortDescription: "Upload any document — PDF, DOCX, or text — and get instant AI-powered summaries, Q&A, key points extraction, and insights.",
    fullDescription: "A powerful document intelligence tool powered by GenAI that processes uploaded documents to extract key information, generate summaries, answer questions about content, highlight important sections, and perform comparative analysis between multiple documents.",
    category: "generative-ai",
    difficulty: "Intermediate",
    isFinalYear: false,
    isFeatured: false,
    technologies: ["Python", "LangChain", "OpenAI", "React", "FastAPI"],
    tags: ["document analysis", "rag", "langchain", "pdf", "generative ai"],
    price: 1299,
    tier: "Professional",
    features: [
      "PDF, DOCX, and TXT document processing",
      "AI-powered document summarization",
      "Q&A over uploaded documents",
      "Key points and entity extraction",
      "Multi-document comparison",
      "Export summaries to PDF",
    ],
    includes: ["Complete source code", "API documentation", "Installation guide", "Portfolio description"],
    learningOutcomes: ["LangChain document loaders", "RAG pipeline basics", "OpenAI embeddings", "FastAPI development"],
    requirements: ["Python 3.10+", "OpenAI API key", "Node.js 18+"],
    modules: [
      { name: "Document Processor", description: "File parsing and chunking pipeline" },
      { name: "Q&A Engine", description: "RAG-based question answering" },
      { name: "Summary Generator", description: "Extractive and abstractive summarization" },
    ],
    techStack: { frontend: ["React"], backend: ["Python", "FastAPI"], aiml: ["LangChain", "OpenAI"] },
    licenseType: "Personal Learning",
    status: "published",
  },

  // ═══════════════════════════════════════
  // AI & ML PROJECTS
  // ═══════════════════════════════════════
  {
    id: "ml-01",
    slug: "student-performance-prediction",
    title: "Student Performance Prediction System",
    shortDescription: "Predicts student exam scores and dropout risk using historical academic data with interactive analytics dashboard.",
    fullDescription: "A complete ML system that analyzes student academic data to predict performance, identify at-risk students, and provide actionable insights to educators. Includes data processing pipeline, trained ML model, REST API, and React dashboard.",
    category: "ai-ml",
    difficulty: "Intermediate",
    isFinalYear: false,
    isFeatured: false,
    technologies: ["Python", "scikit-learn", "React", "Flask", "PostgreSQL"],
    tags: ["machine learning", "prediction", "education", "scikit-learn", "data science"],
    price: 999,
    tier: "Professional",
    features: [
      "Exam score prediction model",
      "Dropout risk classification",
      "Feature importance visualization",
      "Interactive analytics dashboard",
      "REST API for integration",
      "Batch prediction support",
    ],
    includes: ["Source code", "Training notebooks", "Sample dataset", "API documentation", "Installation guide"],
    learningOutcomes: ["ML model training and evaluation", "Feature engineering", "Flask API development", "React dashboards"],
    requirements: ["Python 3.9+", "Node.js 18+", "2GB RAM"],
    modules: [
      { name: "ML Pipeline", description: "Data preprocessing, model training, and evaluation" },
      { name: "Prediction API", description: "REST endpoints for score prediction" },
      { name: "Analytics Dashboard", description: "Visual insights on student performance" },
    ],
    techStack: { frontend: ["React"], backend: ["Python", "Flask"], database: ["PostgreSQL"], aiml: ["scikit-learn", "Pandas"] },
    licenseType: "Personal Learning",
    status: "published",
  },
  {
    id: "ml-02",
    slug: "fake-news-detection-nlp",
    title: "Fake News Detection Using NLP",
    shortDescription: "NLP-powered system that classifies news articles as real or fake with confidence scores and explanations.",
    fullDescription: "A complete NLP system using transformer models to detect fake news articles. Users can paste article text or URLs, and the model classifies authenticity with confidence scores, highlighted suspicious patterns, and model explanations.",
    category: "ai-ml",
    difficulty: "Intermediate",
    isFinalYear: false,
    isFeatured: false,
    technologies: ["Python", "HuggingFace", "React", "FastAPI"],
    tags: ["nlp", "fake news", "transformer", "bert", "text classification"],
    price: 899,
    tier: "Professional",
    features: [
      "Fine-tuned BERT/DistilBERT classifier",
      "URL-based article analysis",
      "Confidence score with explanation",
      "Batch article processing",
      "Simple web interface",
    ],
    includes: ["Source code", "Pre-trained model", "Training notebook", "Installation guide"],
    learningOutcomes: ["HuggingFace Transformers", "Text classification", "Transfer learning", "FastAPI serving"],
    requirements: ["Python 3.9+", "4GB RAM (GPU optional)", "Node.js 18+"],
    modules: [
      { name: "NLP Classifier", description: "Fine-tuned transformer model for fake news detection" },
      { name: "Web Scraper", description: "Article content extraction from URLs" },
      { name: "Analysis API", description: "REST API for classification requests" },
    ],
    techStack: { frontend: ["React"], backend: ["Python", "FastAPI"], aiml: ["HuggingFace", "PyTorch", "NLTK"] },
    licenseType: "Personal Learning",
    status: "published",
  },
  {
    id: "ml-03",
    slug: "customer-churn-prediction",
    title: "Customer Churn Prediction System",
    shortDescription: "Predicts which customers are likely to churn, enabling proactive retention strategies with a complete business analytics dashboard.",
    fullDescription: "A business intelligence ML system that predicts customer churn probability using historical behavior data. Includes model training, real-time prediction API, and an executive dashboard showing churn risk segments and recommended retention actions.",
    category: "ai-ml",
    difficulty: "Beginner",
    isFinalYear: false,
    isFeatured: false,
    technologies: ["Python", "scikit-learn", "React", "Flask"],
    tags: ["machine learning", "churn prediction", "business intelligence", "scikit-learn"],
    price: 699,
    tier: "Starter",
    features: [
      "Churn probability scoring",
      "Customer segmentation by risk level",
      "Feature importance analysis",
      "Retention recommendation engine",
      "Business dashboard with KPIs",
    ],
    includes: ["Source code", "Jupyter notebooks", "Sample dataset", "README", "Installation guide"],
    learningOutcomes: ["Binary classification with scikit-learn", "Business ML applications", "Basic Flask API", "Data visualization"],
    requirements: ["Python 3.9+", "Node.js 18+"],
    modules: [
      { name: "Churn Model", description: "Classification model for churn prediction" },
      { name: "Segmentation", description: "Customer risk level grouping" },
      { name: "Dashboard", description: "Business KPI visualization" },
    ],
    techStack: { frontend: ["React"], backend: ["Python", "Flask"], aiml: ["scikit-learn", "Pandas"] },
    licenseType: "Personal Learning",
    status: "published",
  },

  // ═══════════════════════════════════════
  // FULL STACK PROJECTS
  // ═══════════════════════════════════════
  {
    id: "fs-01",
    slug: "ai-ecommerce-platform",
    title: "AI-Powered E-Commerce Platform",
    shortDescription: "A modern e-commerce platform with AI-powered product recommendations, smart search, personalized shopping experiences, and complete admin panel.",
    fullDescription: "Full-featured e-commerce platform built with Next.js and integrated with AI for smart product recommendations, semantic search, personalized deals, and demand forecasting. Includes complete user authentication, cart, checkout, payment integration, order management, and admin dashboard.",
    category: "full-stack",
    difficulty: "Advanced",
    isFinalYear: false,
    isFeatured: true,
    technologies: ["Next.js", "TypeScript", "PostgreSQL", "Stripe/Razorpay", "OpenAI"],
    tags: ["ecommerce", "nextjs", "full stack", "ai recommendations", "typescript"],
    price: 1999,
    tier: "Premium",
    features: [
      "AI product recommendation engine",
      "Semantic product search",
      "User authentication and profiles",
      "Cart and wishlist",
      "Razorpay payment integration",
      "Order tracking",
      "Admin product management",
      "Inventory management",
      "Analytics dashboard",
      "Mobile-responsive design",
    ],
    includes: [
      "Complete source code",
      "Database schema",
      "API documentation",
      "Admin guide",
      "Installation guide",
      "Architecture diagrams",
      "Portfolio description",
    ],
    learningOutcomes: [
      "Next.js App Router development",
      "E-commerce architecture",
      "Payment gateway integration",
      "AI recommendation systems",
      "PostgreSQL data modeling",
    ],
    requirements: ["Node.js 18+", "PostgreSQL", "Razorpay account"],
    modules: [
      { name: "Product Catalog", description: "Category-based product management with search" },
      { name: "AI Recommendations", description: "Personalized product suggestions" },
      { name: "Checkout & Payment", description: "Cart, address, and Razorpay payment flow" },
      { name: "Admin Panel", description: "Product, order, and user management" },
    ],
    techStack: { frontend: ["Next.js", "TypeScript", "Tailwind CSS"], backend: ["Next.js API Routes"], database: ["PostgreSQL"], aiml: ["OpenAI Embeddings"] },
    licenseType: "Personal Learning",
    status: "published",
  },
  {
    id: "fs-02",
    slug: "online-learning-management-system",
    title: "Online Learning Management System",
    shortDescription: "A comprehensive LMS with course management, video lessons, quizzes, progress tracking, certificates, and admin panel.",
    fullDescription: "A full-featured Learning Management System built with Next.js and Firebase. Instructors can create courses with video lessons, quizzes, and assignments. Students track progress, earn certificates, and participate in discussion forums. Administrators manage everything through a comprehensive dashboard.",
    category: "full-stack",
    difficulty: "Advanced",
    isFinalYear: false,
    isFeatured: false,
    technologies: ["Next.js", "Firebase", "TypeScript", "Tailwind CSS"],
    tags: ["lms", "elearning", "nextjs", "firebase", "full stack"],
    price: 1799,
    tier: "Premium",
    features: [
      "Course creation and management",
      "Video lesson player",
      "Quiz and assignment system",
      "Progress tracking",
      "Certificate generation",
      "Discussion forums",
      "Student and instructor dashboards",
      "Admin panel",
    ],
    includes: ["Complete source code", "Firebase rules", "Documentation", "Installation guide", "Portfolio description"],
    learningOutcomes: ["Next.js full-stack development", "Firebase Firestore", "Video streaming integration", "Certificate generation"],
    requirements: ["Node.js 18+", "Firebase project"],
    modules: [
      { name: "Course Manager", description: "Course creation, lessons, and curriculum builder" },
      { name: "Assessment Engine", description: "Quizzes and assignment grading" },
      { name: "Progress Tracker", description: "Student completion tracking and analytics" },
      { name: "Certificate System", description: "Automated certificate generation" },
    ],
    techStack: { frontend: ["Next.js", "TypeScript", "Tailwind CSS"], backend: ["Next.js", "Firebase"], database: ["Firestore", "Firebase Storage"] },
    licenseType: "Personal Learning",
    status: "published",
  },
  {
    id: "fs-03",
    slug: "job-internship-portal",
    title: "Job & Internship Portal",
    shortDescription: "A full-featured job portal connecting students and freshers with companies for jobs, internships, and campus placements.",
    fullDescription: "A complete recruitment platform where companies post jobs and internships, candidates apply with profiles and resumes, and administrators manage the platform. Features include profile builder, resume upload, application tracking, interview scheduling, and analytics.",
    category: "full-stack",
    difficulty: "Intermediate",
    isFinalYear: false,
    isFeatured: false,
    technologies: ["React", "Node.js", "MongoDB", "Express", "Firebase Auth"],
    tags: ["job portal", "recruitment", "mern stack", "full stack", "internship"],
    price: 1299,
    tier: "Professional",
    features: [
      "Company and candidate registration",
      "Job/internship posting management",
      "Resume upload and profile builder",
      "One-click apply system",
      "Application status tracking",
      "Interview scheduling",
      "Admin dashboard",
    ],
    includes: ["Complete MERN stack source code", "Database schema", "API documentation", "Installation guide"],
    learningOutcomes: ["MERN stack development", "REST API design", "JWT authentication", "File upload handling"],
    requirements: ["Node.js 18+", "MongoDB", "npm"],
    modules: [
      { name: "Job Listings", description: "Company job posting management" },
      { name: "Candidate Portal", description: "Profile builder and application management" },
      { name: "Matching Engine", description: "Skill-based job recommendations" },
      { name: "Admin Panel", description: "Platform management and analytics" },
    ],
    techStack: { frontend: ["React", "Tailwind CSS"], backend: ["Node.js", "Express"], database: ["MongoDB"] },
    licenseType: "Personal Learning",
    status: "published",
  },

  // ═══════════════════════════════════════
  // DATA SCIENCE PROJECTS
  // ═══════════════════════════════════════
  {
    id: "ds-01",
    slug: "business-sales-intelligence-dashboard",
    title: "Business Sales Intelligence Dashboard",
    shortDescription: "Interactive sales analytics dashboard with forecasting, trend analysis, and business insights powered by Python and React.",
    fullDescription: "A comprehensive business intelligence dashboard that processes sales data to provide executives and managers with real-time insights, trend analysis, revenue forecasting, product performance, and regional analytics through beautiful interactive visualizations.",
    category: "data-science",
    difficulty: "Intermediate",
    isFinalYear: false,
    isFeatured: false,
    technologies: ["Python", "Pandas", "React", "Plotly", "FastAPI"],
    tags: ["data science", "business intelligence", "dashboard", "analytics", "visualization"],
    price: 899,
    tier: "Professional",
    features: [
      "Revenue trend analysis",
      "Sales forecasting with ML",
      "Product performance analytics",
      "Regional sales mapping",
      "Customer segmentation",
      "Interactive filters and drill-down",
      "Export to Excel/PDF",
    ],
    includes: ["Source code", "Sample sales dataset", "Jupyter notebooks", "Installation guide"],
    learningOutcomes: ["Python data processing with Pandas", "Data visualization with Plotly", "ML-based forecasting", "FastAPI development"],
    requirements: ["Python 3.9+", "Node.js 18+"],
    modules: [
      { name: "Data Pipeline", description: "Sales data ingestion and transformation" },
      { name: "Analytics Engine", description: "Statistical analysis and forecasting" },
      { name: "Dashboard", description: "Interactive visualization frontend" },
    ],
    techStack: { frontend: ["React", "Plotly.js"], backend: ["Python", "FastAPI"], aiml: ["scikit-learn", "Pandas", "NumPy"] },
    licenseType: "Personal Learning",
    status: "published",
  },
  {
    id: "ds-02",
    slug: "customer-segmentation-system",
    title: "Customer Segmentation System",
    shortDescription: "ML-powered customer segmentation using clustering algorithms to identify valuable customer groups for targeted marketing.",
    fullDescription: "A data science project that applies K-Means, hierarchical clustering, and DBSCAN to segment customers based on purchase behavior, demographics, and engagement patterns. Includes interactive visualization, segment profiling, and marketing recommendation engine.",
    category: "data-science",
    difficulty: "Beginner",
    isFinalYear: false,
    isFeatured: false,
    technologies: ["Python", "scikit-learn", "React", "Plotly"],
    tags: ["clustering", "customer segmentation", "machine learning", "data science", "kmeans"],
    price: 699,
    tier: "Starter",
    features: [
      "K-Means and hierarchical clustering",
      "Elbow method for optimal clusters",
      "Customer segment profiling",
      "RFM analysis (Recency, Frequency, Monetary)",
      "Interactive cluster visualization",
      "Marketing recommendation per segment",
    ],
    includes: ["Source code", "Jupyter notebooks", "Sample dataset", "README"],
    learningOutcomes: ["Clustering algorithms", "RFM analysis", "Data preprocessing", "Plotly visualization"],
    requirements: ["Python 3.9+"],
    modules: [
      { name: "Clustering Engine", description: "Multiple clustering algorithms implementation" },
      { name: "Segment Profiler", description: "Automated segment characterization" },
      { name: "Visualization", description: "2D/3D cluster plots and segment dashboards" },
    ],
    techStack: { frontend: ["React"], backend: ["Python", "Flask"], aiml: ["scikit-learn", "Pandas"] },
    licenseType: "Personal Learning",
    status: "published",
  },

  // ═══════════════════════════════════════
  // COMPUTER VISION
  // ═══════════════════════════════════════
  {
    id: "cv-01",
    slug: "face-recognition-attendance-system",
    title: "Face Recognition Attendance System",
    shortDescription: "Automated attendance marking system using real-time face recognition from webcam or camera feeds.",
    fullDescription: "A production-ready face recognition system that automates attendance marking. The system registers employee/student faces, then identifies them in real-time from camera feeds to mark attendance automatically. Includes admin dashboard, attendance reports, and export features.",
    category: "computer-vision",
    difficulty: "Intermediate",
    isFinalYear: false,
    isFeatured: true,
    technologies: ["Python", "OpenCV", "DeepFace", "React", "SQLite"],
    tags: ["face recognition", "attendance", "opencv", "computer vision", "deepface"],
    price: 1299,
    tier: "Professional",
    features: [
      "Real-time face detection and recognition",
      "Face registration with multiple angles",
      "Automatic attendance marking",
      "Attendance dashboard and reports",
      "Unknown face alerts",
      "Export attendance to Excel",
      "Multiple camera support",
    ],
    includes: ["Complete source code", "Setup guide for face registration", "API documentation", "Installation guide"],
    learningOutcomes: ["OpenCV face detection", "Deep face recognition models", "Real-time video processing", "SQLite database"],
    requirements: ["Python 3.9+", "Webcam", "Node.js 18+", "4GB RAM"],
    modules: [
      { name: "Face Engine", description: "Detection and recognition using DeepFace" },
      { name: "Registration Module", description: "Face dataset management" },
      { name: "Attendance Tracker", description: "Automated marking and reporting" },
    ],
    techStack: { frontend: ["React"], backend: ["Python", "FastAPI"], database: ["SQLite"], aiml: ["OpenCV", "DeepFace"] },
    licenseType: "Personal Learning",
    status: "published",
  },
  {
    id: "cv-02",
    slug: "ai-sign-language-recognition",
    title: "AI Sign Language Recognition",
    shortDescription: "Real-time sign language gesture recognition using CNN and MediaPipe to convert hand signs to text — making communication accessible.",
    fullDescription: "An accessibility-focused computer vision project that uses MediaPipe for hand landmark detection and a trained CNN classifier to recognize ASL (American Sign Language) gestures in real-time from webcam input. Converts recognized signs to text and speech.",
    category: "computer-vision",
    difficulty: "Intermediate",
    isFinalYear: false,
    isFeatured: false,
    technologies: ["Python", "MediaPipe", "TensorFlow", "OpenCV", "React"],
    tags: ["sign language", "mediapipe", "gesture recognition", "computer vision", "accessibility"],
    price: 999,
    tier: "Professional",
    features: [
      "Real-time hand landmark detection",
      "ASL alphabet recognition",
      "Word and sentence formation",
      "Text-to-speech output",
      "Training pipeline for new gestures",
      "Web interface with live preview",
    ],
    includes: ["Source code", "Pre-trained model", "Training scripts", "Installation guide"],
    learningOutcomes: ["MediaPipe for hand tracking", "CNN classifier training", "Real-time video pipeline", "Accessibility AI"],
    requirements: ["Python 3.9+", "Webcam", "TensorFlow 2.x"],
    modules: [
      { name: "Hand Detector", description: "MediaPipe landmark extraction" },
      { name: "Gesture Classifier", description: "CNN model for sign recognition" },
      { name: "Text Builder", description: "Sign-to-word-to-sentence conversion" },
    ],
    techStack: { frontend: ["React"], backend: ["Python", "FastAPI"], aiml: ["TensorFlow", "MediaPipe", "OpenCV"] },
    licenseType: "Personal Learning",
    status: "published",
  },

  // ═══════════════════════════════════════
  // CYBERSECURITY
  // ═══════════════════════════════════════
  {
    id: "sec-01",
    slug: "phishing-website-detection",
    title: "Phishing Website Detection System",
    shortDescription: "ML-powered browser extension and web tool that detects phishing websites in real-time by analyzing URL features and page content.",
    fullDescription: "A complete cybersecurity ML project that extracts URL features, analyzes domain characteristics, and applies a trained classifier to detect phishing websites with high accuracy. Includes a Chrome extension, web dashboard, and REST API.",
    category: "cybersecurity",
    difficulty: "Intermediate",
    isFinalYear: false,
    isFeatured: false,
    technologies: ["Python", "scikit-learn", "JavaScript", "Chrome Extension API", "FastAPI"],
    tags: ["phishing", "cybersecurity", "machine learning", "browser extension", "url analysis"],
    price: 999,
    tier: "Professional",
    features: [
      "URL feature extraction (55+ features)",
      "Real-time phishing detection",
      "Chrome extension integration",
      "Web dashboard for bulk scanning",
      "Model training pipeline",
      "REST API for integration",
    ],
    includes: ["Source code (Python + Extension)", "Pre-trained model", "Feature documentation", "Installation guide"],
    learningOutcomes: ["URL feature engineering", "ML for security", "Chrome extension development", "FastAPI"],
    requirements: ["Python 3.9+", "Chrome browser for extension"],
    modules: [
      { name: "Feature Extractor", description: "URL and domain feature analysis" },
      { name: "ML Classifier", description: "Trained phishing detection model" },
      { name: "Chrome Extension", description: "Real-time browser protection" },
      { name: "Web Scanner", description: "Bulk URL analysis dashboard" },
    ],
    techStack: { frontend: ["React", "JavaScript (Extension)"], backend: ["Python", "FastAPI"], aiml: ["scikit-learn", "XGBoost"] },
    licenseType: "Personal Learning",
    status: "published",
  },

  // ═══════════════════════════════════════
  // CLOUD & DEVOPS
  // ═══════════════════════════════════════
  {
    id: "cloud-01",
    slug: "cloud-file-storage-sharing",
    title: "Cloud File Storage & Sharing Platform",
    shortDescription: "A Google Drive-like cloud storage platform with file upload, sharing, folder management, and access control built on Firebase.",
    fullDescription: "Build your own cloud storage platform with file upload, download, sharing with granular permissions, folder organization, preview support, and activity logging. Built with Next.js and Firebase Storage.",
    category: "cloud-devops",
    difficulty: "Intermediate",
    isFinalYear: false,
    isFeatured: false,
    technologies: ["Next.js", "Firebase", "TypeScript", "Tailwind CSS"],
    tags: ["cloud storage", "firebase", "file sharing", "nextjs", "full stack"],
    price: 999,
    tier: "Professional",
    features: [
      "File upload with drag-and-drop",
      "Folder organization",
      "File sharing with permissions",
      "Preview for images, PDFs, videos",
      "Storage quota management",
      "Activity log",
      "Public/private links",
    ],
    includes: ["Source code", "Firebase rules", "Installation guide", "Portfolio description"],
    learningOutcomes: ["Firebase Storage", "File management systems", "Access control", "Next.js development"],
    requirements: ["Node.js 18+", "Firebase project"],
    modules: [
      { name: "File Manager", description: "Upload, organize, and manage files" },
      { name: "Sharing System", description: "Permission-based access control" },
      { name: "Preview Engine", description: "In-browser file preview" },
    ],
    techStack: { frontend: ["Next.js", "TypeScript", "Tailwind CSS"], backend: ["Next.js", "Firebase"], database: ["Firestore", "Firebase Storage"] },
    licenseType: "Personal Learning",
    status: "published",
  },

  // ═══════════════════════════════════════
  // MOBILE
  // ═══════════════════════════════════════
  {
    id: "mob-01",
    slug: "ai-personal-expense-manager",
    title: "AI Personal Expense Manager",
    shortDescription: "A smart personal finance app that automatically categorizes expenses, detects spending patterns, and provides AI-powered budgeting advice.",
    fullDescription: "A personal finance management web application with AI-powered expense categorization, spending pattern analysis, budget tracking, goal setting, and personalized financial recommendations. Features clean mobile-first design with intuitive data entry.",
    category: "mobile",
    difficulty: "Intermediate",
    isFinalYear: false,
    isFeatured: false,
    technologies: ["React Native", "Python", "Firebase", "OpenAI"],
    tags: ["personal finance", "expense tracker", "ai", "mobile", "react native"],
    price: 899,
    tier: "Professional",
    features: [
      "AI-powered expense categorization",
      "Budget creation and tracking",
      "Spending pattern analysis",
      "Financial goal setting",
      "Monthly report generation",
      "Personalized saving suggestions",
    ],
    includes: ["Complete source code", "Firebase setup", "Installation guide", "Portfolio description"],
    learningOutcomes: ["React Native or React mobile-first design", "Firebase Firestore", "OpenAI API integration", "Financial data visualization"],
    requirements: ["Node.js 18+", "Firebase project", "OpenAI API key"],
    modules: [
      { name: "Expense Tracker", description: "Transaction entry and categorization" },
      { name: "AI Advisor", description: "Pattern analysis and budgeting suggestions" },
      { name: "Reports", description: "Monthly/yearly financial summaries" },
    ],
    techStack: { frontend: ["React", "Tailwind CSS"], backend: ["Firebase"], database: ["Firestore"], aiml: ["OpenAI"] },
    licenseType: "Personal Learning",
    status: "published",
  },

  // ═══════════════════════════════════════
  // AI AGENTS
  // ═══════════════════════════════════════
  {
    id: "agent-01",
    slug: "ai-customer-support-agent",
    title: "AI Customer Support Agent",
    shortDescription: "An intelligent customer support agent that handles queries autonomously, escalates when needed, and learns from interactions.",
    fullDescription: "A production-ready AI customer support system with an LLM-powered agent that understands customer queries, searches knowledge bases, retrieves order information, handles returns/refunds queries, and escalates complex issues to human agents.",
    category: "ai-agents",
    difficulty: "Intermediate",
    isFinalYear: false,
    isFeatured: true,
    technologies: ["Python", "LangChain", "OpenAI", "React", "FastAPI"],
    tags: ["ai agents", "customer support", "chatbot", "langchain", "automation"],
    price: 1299,
    tier: "Professional",
    features: [
      "LLM-powered conversational agent",
      "Knowledge base integration",
      "Order status lookup tool",
      "Human escalation workflow",
      "Conversation analytics",
      "Customizable response templates",
      "Multi-channel support (web, API)",
    ],
    includes: ["Complete source code", "Agent configuration guide", "Knowledge base setup", "API documentation", "Installation guide"],
    learningOutcomes: ["AI agent design patterns", "LangChain tool use", "Customer support automation", "Conversation design"],
    requirements: ["Python 3.10+", "OpenAI API key", "Node.js 18+"],
    modules: [
      { name: "Support Agent", description: "LangChain agent with multiple tools" },
      { name: "Knowledge Base", description: "RAG-powered FAQ and documentation search" },
      { name: "Escalation System", description: "Human handoff workflow" },
      { name: "Analytics", description: "Conversation metrics and insights" },
    ],
    techStack: { frontend: ["React"], backend: ["Python", "FastAPI", "LangChain"], database: ["SQLite"], aiml: ["OpenAI", "LangChain"] },
    licenseType: "Personal Learning",
    status: "published",
  },
];

// Get projects by category
export function getProjectsByCategory(categoryId: string): Project[] {
  return PROJECTS.filter((p) => p.category === categoryId && p.status === "published");
}

// Get final year projects
export function getFinalYearProjects(): Project[] {
  return PROJECTS.filter((p) => p.isFinalYear && p.status === "published");
}

// Get featured projects
export function getFeaturedProjects(): Project[] {
  return PROJECTS.filter((p) => p.isFeatured && p.status === "published");
}

// Get project by slug
export function getProjectBySlug(slug: string): Project | undefined {
  return PROJECTS.find((p) => p.slug === slug && p.status === "published");
}

// Get related projects
export function getRelatedProjects(project: Project, limit = 4): Project[] {
  return PROJECTS.filter(
    (p) =>
      p.id !== project.id &&
      p.status === "published" &&
      (p.category === project.category ||
        p.technologies.some((t) => project.technologies.includes(t)))
  ).slice(0, limit);
}

export const PROJECT_PACKS: ProjectPack[] = [
  {
    id: "ai-starter-pack",
    name: "AI Starter Pack",
    description: "5 beginner-friendly AI/ML projects to kickstart your AI journey",
    projects: ["customer-churn-prediction", "student-performance-prediction", "customer-segmentation-system", "fake-news-detection-nlp", "phishing-website-detection"],
    price: 2499,
    features: ["5 complete projects", "Source code + documentation", "Installation guides", "Portfolio descriptions"],
    badge: "Best for Beginners",
  },
  {
    id: "generative-ai-pack",
    name: "Generative AI Pack",
    description: "10 cutting-edge GenAI projects covering LLMs, RAG, agents, and more",
    projects: ["ai-college-assistant-rag", "ai-interview-preparation-system", "ai-document-analyzer", "multi-agent-ai-research-assistant", "ai-customer-support-agent"],
    price: 6999,
    features: ["5 GenAI projects", "Complete documentation", "API keys setup guides", "Viva preparation"],
    badge: "Most Popular",
  },
  {
    id: "final-year-ai-pack",
    name: "Final Year AI Pack",
    description: "10 advanced final year projects with complete documentation, PPTs, and viva prep",
    projects: ["ai-smart-hospital-management", "ai-college-assistant-rag", "ai-resume-screening-job-matching", "smart-campus-management-ai", "ai-fraud-detection-financial-risk", "intelligent-traffic-monitoring-accident-detection", "ai-crop-disease-detection-agriculture", "ai-cybersecurity-threat-phishing-detection", "multi-agent-ai-research-assistant", "ai-personalized-learning-performance-prediction"],
    price: 14999,
    features: ["All 10 final year projects", "Full documentation suite", "PPT for each project", "Viva Q&A", "Architecture diagrams", "Portfolio support"],
    badge: "Best Value",
  },
  {
    id: "full-stack-pack",
    name: "Full Stack Pack",
    description: "5 complete full-stack projects using modern tech stacks",
    projects: ["ai-ecommerce-platform", "online-learning-management-system", "job-internship-portal", "cloud-file-storage-sharing", "smart-campus-management-ai"],
    price: 4999,
    features: ["5 full-stack projects", "Source code", "Deployment guides", "Documentation"],
  },
];
